//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3Tools {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("C3Tools.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        public static byte[] pinned {
            get {
                object obj = ResourceManager.GetObject("pinned", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] unpinned {
            get {
                object obj = ResourceManager.GetObject("unpinned", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] working {
            get {
                object obj = ResourceManager.GetObject("working", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] c3banner {
            get {
                object obj = ResourceManager.GetObject("c3banner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bg3 {
            get {
                object obj = ResourceManager.GetObject("bg3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] KV {
            get {
                object obj = ResourceManager.GetObject("KV", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
