//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3Tools.x360 {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("x360.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] XK0 {
            get {
                object obj = ResourceManager.GetObject("XK0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] XK1 {
            get {
                object obj = ResourceManager.GetObject("XK1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] XK2 {
            get {
                object obj = ResourceManager.GetObject("XK2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] XK3 {
            get {
                object obj = ResourceManager.GetObject("XK3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] XK4 {
            get {
                object obj = ResourceManager.GetObject("XK4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] XK5 {
            get {
                object obj = ResourceManager.GetObject("XK5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] XK6 {
            get {
                object obj = ResourceManager.GetObject("XK6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] RB3 {
            get {
                object obj = ResourceManager.GetObject("RB3", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
